# Makefile.in generated by automake 1.10.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/codec_g72x
pkglibdir = $(libdir)/codec_g72x
pkgincludedir = $(includedir)/codec_g72x
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure compile config.guess config.sub \
	depcomp install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_check_compiler_flags.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(moddir)"
modLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(mod_LTLIBRARIES)
codec_g723_la_DEPENDENCIES =
am__codec_g723_la_SOURCES_DIST = codec_g72x.c ipp/decg723.c \
	ipp/encg723.c ipp/owng723.c ipp/vadg723.c ipp/aux_tbls.c \
	itu/g.723.1a/basop.c itu/g.723.1a/cod_cng.c \
	itu/g.723.1a/coder.c itu/g.723.1a/dec_cng.c \
	itu/g.723.1a/decod.c itu/g.723.1a/exc_lbc.c itu/g.723.1a/lpc.c \
	itu/g.723.1a/lsp.c itu/g.723.1a/tab_lbc.c itu/g.723.1a/tame.c \
	itu/g.723.1a/util_cng.c itu/g.723.1a/util_lbc.c \
	itu/g.723.1a/vad.c
am__dirstamp = $(am__leading_dot)dirstamp
am_codec_g723_la_OBJECTS =  \
	codec_g723_la-codec_g72x.lo \
	ipp/codec_g723_la-decg723.lo \
	ipp/codec_g723_la-encg723.lo \
	ipp/codec_g723_la-owng723.lo \
	ipp/codec_g723_la-vadg723.lo \
	ipp/codec_g723_la-aux_tbls.lo
#am_codec_g723_la_OBJECTS = codec_g723_la-codec_g72x.lo \
#	itu/g.723.1a/codec_g723_la-basop.lo \
#	itu/g.723.1a/codec_g723_la-cod_cng.lo \
#	itu/g.723.1a/codec_g723_la-coder.lo \
#	itu/g.723.1a/codec_g723_la-dec_cng.lo \
#	itu/g.723.1a/codec_g723_la-decod.lo \
#	itu/g.723.1a/codec_g723_la-exc_lbc.lo \
#	itu/g.723.1a/codec_g723_la-lpc.lo \
#	itu/g.723.1a/codec_g723_la-lsp.lo \
#	itu/g.723.1a/codec_g723_la-tab_lbc.lo \
#	itu/g.723.1a/codec_g723_la-tame.lo \
#	itu/g.723.1a/codec_g723_la-util_cng.lo \
#	itu/g.723.1a/codec_g723_la-util_lbc.lo \
#	itu/g.723.1a/codec_g723_la-vad.lo
codec_g723_la_OBJECTS = $(am_codec_g723_la_OBJECTS)
codec_g723_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(codec_g723_la_CFLAGS) \
	$(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
#am_codec_g723_la_rpath = -rpath $(moddir)
am_codec_g723_la_rpath = -rpath $(moddir)
codec_g729_la_DEPENDENCIES =
am__codec_g729_la_SOURCES_DIST = codec_g72x.c ipp/decg729fp.c \
	ipp/encg729fp.c ipp/owng729fp.c ipp/vadg729fp.c \
	itu/g.729a/acelp_ca.c itu/g.729a/basic_op.c \
	itu/g.729a/cod_ld8a.c itu/g.729a/cor_func.c \
	itu/g.729a/de_acelp.c itu/g.729a/dec_gain.c \
	itu/g.729a/dec_lag3.c itu/g.729a/dec_ld8a.c \
	itu/g.729a/dspfunc.c itu/g.729a/filter.c itu/g.729a/gainpred.c \
	itu/g.729a/lpc.c itu/g.729a/lpcfunc.c itu/g.729a/lspdec.c \
	itu/g.729a/lspgetq.c itu/g.729a/oper_32b.c \
	itu/g.729a/p_parity.c itu/g.729a/pitch_a.c \
	itu/g.729a/post_pro.c itu/g.729a/postfilt.c \
	itu/g.729a/pre_proc.c itu/g.729a/pred_lt3.c \
	itu/g.729a/qua_gain.c itu/g.729a/qua_lsp.c \
	itu/g.729a/tab_ld8a.c itu/g.729a/taming.c itu/g.729a/util.c
am_codec_g729_la_OBJECTS =  \
	codec_g729_la-codec_g72x.lo \
	ipp/codec_g729_la-decg729fp.lo \
	ipp/codec_g729_la-encg729fp.lo \
	ipp/codec_g729_la-owng729fp.lo \
	ipp/codec_g729_la-vadg729fp.lo
#am_codec_g729_la_OBJECTS = codec_g729_la-codec_g72x.lo \
#	itu/g.729a/codec_g729_la-acelp_ca.lo \
#	itu/g.729a/codec_g729_la-basic_op.lo \
#	itu/g.729a/codec_g729_la-cod_ld8a.lo \
#	itu/g.729a/codec_g729_la-cor_func.lo \
#	itu/g.729a/codec_g729_la-de_acelp.lo \
#	itu/g.729a/codec_g729_la-dec_gain.lo \
#	itu/g.729a/codec_g729_la-dec_lag3.lo \
#	itu/g.729a/codec_g729_la-dec_ld8a.lo \
#	itu/g.729a/codec_g729_la-dspfunc.lo \
#	itu/g.729a/codec_g729_la-filter.lo \
#	itu/g.729a/codec_g729_la-gainpred.lo \
#	itu/g.729a/codec_g729_la-lpc.lo \
#	itu/g.729a/codec_g729_la-lpcfunc.lo \
#	itu/g.729a/codec_g729_la-lspdec.lo \
#	itu/g.729a/codec_g729_la-lspgetq.lo \
#	itu/g.729a/codec_g729_la-oper_32b.lo \
#	itu/g.729a/codec_g729_la-p_parity.lo \
#	itu/g.729a/codec_g729_la-pitch_a.lo \
#	itu/g.729a/codec_g729_la-post_pro.lo \
#	itu/g.729a/codec_g729_la-postfilt.lo \
#	itu/g.729a/codec_g729_la-pre_proc.lo \
#	itu/g.729a/codec_g729_la-pred_lt3.lo \
#	itu/g.729a/codec_g729_la-qua_gain.lo \
#	itu/g.729a/codec_g729_la-qua_lsp.lo \
#	itu/g.729a/codec_g729_la-tab_ld8a.lo \
#	itu/g.729a/codec_g729_la-taming.lo \
#	itu/g.729a/codec_g729_la-util.lo
codec_g729_la_OBJECTS = $(am_codec_g729_la_OBJECTS)
codec_g729_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(codec_g729_la_CFLAGS) \
	$(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
#am_codec_g729_la_rpath = -rpath $(moddir)
codec_g729nofp_la_DEPENDENCIES =
am__codec_g729nofp_la_SOURCES_DIST = codec_g72x.c ipp/decg729.c \
	ipp/encg729.c ipp/owng729.c ipp/vadg729.c ipp/aux_tbls.c
am_codec_g729nofp_la_OBJECTS =  \
	codec_g729nofp_la-codec_g72x.lo \
	ipp/codec_g729nofp_la-decg729.lo \
	ipp/codec_g729nofp_la-encg729.lo \
	ipp/codec_g729nofp_la-owng729.lo \
	ipp/codec_g729nofp_la-vadg729.lo \
	ipp/codec_g729nofp_la-aux_tbls.lo
codec_g729nofp_la_OBJECTS = $(am_codec_g729nofp_la_OBJECTS)
codec_g729nofp_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(codec_g729nofp_la_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
am_codec_g729nofp_la_rpath = -rpath $(moddir)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(codec_g723_la_SOURCES) $(codec_g729_la_SOURCES) \
	$(codec_g729nofp_la_SOURCES)
DIST_SOURCES = $(am__codec_g723_la_SOURCES_DIST) \
	$(am__codec_g729_la_SOURCES_DIST) \
	$(am__codec_g729nofp_la_SOURCES_DIST)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2/missing --run aclocal-1.10
AMTAR = ${SHELL} /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2/missing --run tar
AR = ar
ASTERISK_ASTERISK_H = 
ASTERISK_CFLAGS = -I"/home/arkadi/opt/asterisk-1.8.0/include"
ASTERISK_VERSION = 18
AUTOCONF = ${SHELL} /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2/missing --run autoconf
AUTOHEADER = ${SHELL} /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2/missing --run autoheader
AUTOMAKE = ${SHELL} /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2/missing --run automake-1.10
AWK = gawk
CALLWEAVER_CFLAGS = 
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -O3 -fomit-frame-pointer -march=geode -flto 
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
FLTO_LDFLAGS = -fwhole-program
G72X_9_NOFP = -DG72X_9_NOFP
G72X_ITU = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
IPP_CFLAGS = -I"/opt/intel/_save/ipp/6.1/ia32/include" -DIPPCORE_NO_SSE -include "/opt/intel/_save/ipp/6.1/ia32/tools/staticlib/ipp_px.h"
IPP_LDFLAGS = -L"/opt/intel/_save/ipp/6.1/ia32/lib"
IPP_LIBS = -lippscmerged -lippsrmerged -lippsmerged -lippcore
LD = /usr/i686-pc-linux-gnu/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = codec_g72x
PACKAGE_BUGREPORT = http://groups.google.com/group/asterisk-g729
PACKAGE_NAME = codec_g72x
PACKAGE_STRING = codec_g72x 1.1-beta1
PACKAGE_TARNAME = codec_g72x
PACKAGE_URL = 
PACKAGE_VERSION = 1.1-beta1
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 1.1-beta1
abs_builddir = /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2
abs_srcdir = /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2
abs_top_builddir = /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2
abs_top_srcdir = /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /home/arkadi/work/g72x/asterisk-g72x-1.1-beta2/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign subdir-objects
AM_CFLAGS =  -DG72X_ASTERISK=18 -I"/home/arkadi/opt/asterisk-1.8.0/include" \
              -I"/opt/intel/_save/ipp/6.1/ia32/include" -DIPPCORE_NO_SSE -include "/opt/intel/_save/ipp/6.1/ia32/tools/staticlib/ipp_px.h"  \
             -Wall -D_GNU_SOURCE

AM_LDFLAGS = -L"/opt/intel/_save/ipp/6.1/ia32/lib" -fwhole-program -avoid-version -module
ACLOCAL_AMFLAGS = -I m4
moddir = ${libdir}/asterisk/modules
#mod_LTLIBRARIES = codec_g723.la codec_g729.la
mod_LTLIBRARIES = codec_g723.la codec_g729nofp.la
codec_g723_la_CFLAGS = ${AM_CFLAGS} -Iipp -DG72X_3
#codec_g723_la_CFLAGS = ${AM_CFLAGS} -Iitu/g.723.1a -DG72X_3
codec_g723_la_SOURCES = codec_g72x.c ipp/decg723.c ipp/encg723.c ipp/owng723.c ipp/vadg723.c ipp/aux_tbls.c
#codec_g723_la_SOURCES = codec_g72x.c \
#	itu/g.723.1a/basop.c \
#	itu/g.723.1a/cod_cng.c \
#	itu/g.723.1a/coder.c \
#	itu/g.723.1a/dec_cng.c \
#	itu/g.723.1a/decod.c \
#	itu/g.723.1a/exc_lbc.c \
#	itu/g.723.1a/lpc.c \
#	itu/g.723.1a/lsp.c \
#	itu/g.723.1a/tab_lbc.c \
#	itu/g.723.1a/tame.c \
#	itu/g.723.1a/util_cng.c \
#	itu/g.723.1a/util_lbc.c \
#	itu/g.723.1a/vad.c

codec_g729_la_CFLAGS = ${AM_CFLAGS} -Iipp -DG72X_9
#codec_g729_la_CFLAGS = ${AM_CFLAGS} -Iitu/g.729a -DG72X_9
codec_g729_la_SOURCES = codec_g72x.c ipp/decg729fp.c ipp/encg729fp.c ipp/owng729fp.c ipp/vadg729fp.c
#codec_g729_la_SOURCES = codec_g72x.c \
#	itu/g.729a/acelp_ca.c \
#	itu/g.729a/basic_op.c \
#	itu/g.729a/cod_ld8a.c \
#	itu/g.729a/cor_func.c \
#	itu/g.729a/de_acelp.c \
#	itu/g.729a/dec_gain.c \
#	itu/g.729a/dec_lag3.c \
#	itu/g.729a/dec_ld8a.c \
#	itu/g.729a/dspfunc.c \
#	itu/g.729a/filter.c \
#	itu/g.729a/gainpred.c \
#	itu/g.729a/lpc.c \
#	itu/g.729a/lpcfunc.c \
#	itu/g.729a/lspdec.c \
#	itu/g.729a/lspgetq.c \
#	itu/g.729a/oper_32b.c \
#	itu/g.729a/p_parity.c \
#	itu/g.729a/pitch_a.c \
#	itu/g.729a/post_pro.c \
#	itu/g.729a/postfilt.c \
#	itu/g.729a/pre_proc.c \
#	itu/g.729a/pred_lt3.c \
#	itu/g.729a/qua_gain.c \
#	itu/g.729a/qua_lsp.c \
#	itu/g.729a/tab_ld8a.c \
#	itu/g.729a/taming.c \
#	itu/g.729a/util.c

codec_g723_la_LIBADD = -lippscmerged -lippsrmerged -lippsmerged -lippcore
codec_g729_la_LIBADD = -lippscmerged -lippsrmerged -lippsmerged -lippcore
codec_g729nofp_la_SOURCES = codec_g72x.c ipp/decg729.c ipp/encg729.c ipp/owng729.c ipp/vadg729.c ipp/aux_tbls.c
codec_g729nofp_la_CFLAGS = ${AM_CFLAGS} -Iipp -DG72X_9 -DG72X_9_NOFP
codec_g729nofp_la_LIBADD = -lippscmerged -lippsrmerged -lippsmerged -lippcore
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign '; \
	      cd $(srcdir) && $(AUTOMAKE) --foreign  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-modLTLIBRARIES: $(mod_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(moddir)" || $(MKDIR_P) "$(DESTDIR)$(moddir)"
	@list='$(mod_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(modLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(moddir)/$$f'"; \
	    $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(modLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(moddir)/$$f"; \
	  else :; fi; \
	done

uninstall-modLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(mod_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(moddir)/$$p'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(moddir)/$$p"; \
	done

clean-modLTLIBRARIES:
	-test -z "$(mod_LTLIBRARIES)" || rm -f $(mod_LTLIBRARIES)
	@list='$(mod_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
ipp/$(am__dirstamp):
	@$(MKDIR_P) ipp
	@: > ipp/$(am__dirstamp)
ipp/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) ipp/$(DEPDIR)
	@: > ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g723_la-decg723.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g723_la-encg723.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g723_la-owng723.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g723_la-vadg723.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g723_la-aux_tbls.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/$(am__dirstamp):
	@$(MKDIR_P) itu/g.723.1a
	@: > itu/g.723.1a/$(am__dirstamp)
itu/g.723.1a/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) itu/g.723.1a/$(DEPDIR)
	@: > itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-basop.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-cod_cng.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-coder.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-dec_cng.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-decod.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-exc_lbc.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-lpc.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-lsp.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-tab_lbc.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-tame.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-util_cng.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-util_lbc.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
itu/g.723.1a/codec_g723_la-vad.lo: itu/g.723.1a/$(am__dirstamp) \
	itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
codec_g723.la: $(codec_g723_la_OBJECTS) $(codec_g723_la_DEPENDENCIES) 
	$(codec_g723_la_LINK) $(am_codec_g723_la_rpath) $(codec_g723_la_OBJECTS) $(codec_g723_la_LIBADD) $(LIBS)
ipp/codec_g729_la-decg729fp.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g729_la-encg729fp.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g729_la-owng729fp.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g729_la-vadg729fp.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/$(am__dirstamp):
	@$(MKDIR_P) itu/g.729a
	@: > itu/g.729a/$(am__dirstamp)
itu/g.729a/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) itu/g.729a/$(DEPDIR)
	@: > itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-acelp_ca.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-basic_op.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-cod_ld8a.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-cor_func.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-de_acelp.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-dec_gain.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-dec_lag3.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-dec_ld8a.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-dspfunc.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-filter.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-gainpred.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-lpc.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-lpcfunc.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-lspdec.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-lspgetq.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-oper_32b.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-p_parity.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-pitch_a.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-post_pro.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-postfilt.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-pre_proc.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-pred_lt3.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-qua_gain.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-qua_lsp.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-tab_ld8a.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-taming.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
itu/g.729a/codec_g729_la-util.lo: itu/g.729a/$(am__dirstamp) \
	itu/g.729a/$(DEPDIR)/$(am__dirstamp)
codec_g729.la: $(codec_g729_la_OBJECTS) $(codec_g729_la_DEPENDENCIES) 
	$(codec_g729_la_LINK) $(am_codec_g729_la_rpath) $(codec_g729_la_OBJECTS) $(codec_g729_la_LIBADD) $(LIBS)
ipp/codec_g729nofp_la-decg729.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g729nofp_la-encg729.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g729nofp_la-owng729.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g729nofp_la-vadg729.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
ipp/codec_g729nofp_la-aux_tbls.lo: ipp/$(am__dirstamp) \
	ipp/$(DEPDIR)/$(am__dirstamp)
codec_g729nofp.la: $(codec_g729nofp_la_OBJECTS) $(codec_g729nofp_la_DEPENDENCIES) 
	$(codec_g729nofp_la_LINK) $(am_codec_g729nofp_la_rpath) $(codec_g729nofp_la_OBJECTS) $(codec_g729nofp_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f ipp/codec_g723_la-aux_tbls.$(OBJEXT)
	-rm -f ipp/codec_g723_la-aux_tbls.lo
	-rm -f ipp/codec_g723_la-decg723.$(OBJEXT)
	-rm -f ipp/codec_g723_la-decg723.lo
	-rm -f ipp/codec_g723_la-encg723.$(OBJEXT)
	-rm -f ipp/codec_g723_la-encg723.lo
	-rm -f ipp/codec_g723_la-owng723.$(OBJEXT)
	-rm -f ipp/codec_g723_la-owng723.lo
	-rm -f ipp/codec_g723_la-vadg723.$(OBJEXT)
	-rm -f ipp/codec_g723_la-vadg723.lo
	-rm -f ipp/codec_g729_la-decg729fp.$(OBJEXT)
	-rm -f ipp/codec_g729_la-decg729fp.lo
	-rm -f ipp/codec_g729_la-encg729fp.$(OBJEXT)
	-rm -f ipp/codec_g729_la-encg729fp.lo
	-rm -f ipp/codec_g729_la-owng729fp.$(OBJEXT)
	-rm -f ipp/codec_g729_la-owng729fp.lo
	-rm -f ipp/codec_g729_la-vadg729fp.$(OBJEXT)
	-rm -f ipp/codec_g729_la-vadg729fp.lo
	-rm -f ipp/codec_g729nofp_la-aux_tbls.$(OBJEXT)
	-rm -f ipp/codec_g729nofp_la-aux_tbls.lo
	-rm -f ipp/codec_g729nofp_la-decg729.$(OBJEXT)
	-rm -f ipp/codec_g729nofp_la-decg729.lo
	-rm -f ipp/codec_g729nofp_la-encg729.$(OBJEXT)
	-rm -f ipp/codec_g729nofp_la-encg729.lo
	-rm -f ipp/codec_g729nofp_la-owng729.$(OBJEXT)
	-rm -f ipp/codec_g729nofp_la-owng729.lo
	-rm -f ipp/codec_g729nofp_la-vadg729.$(OBJEXT)
	-rm -f ipp/codec_g729nofp_la-vadg729.lo
	-rm -f itu/g.723.1a/codec_g723_la-basop.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-basop.lo
	-rm -f itu/g.723.1a/codec_g723_la-cod_cng.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-cod_cng.lo
	-rm -f itu/g.723.1a/codec_g723_la-coder.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-coder.lo
	-rm -f itu/g.723.1a/codec_g723_la-dec_cng.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-dec_cng.lo
	-rm -f itu/g.723.1a/codec_g723_la-decod.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-decod.lo
	-rm -f itu/g.723.1a/codec_g723_la-exc_lbc.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-exc_lbc.lo
	-rm -f itu/g.723.1a/codec_g723_la-lpc.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-lpc.lo
	-rm -f itu/g.723.1a/codec_g723_la-lsp.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-lsp.lo
	-rm -f itu/g.723.1a/codec_g723_la-tab_lbc.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-tab_lbc.lo
	-rm -f itu/g.723.1a/codec_g723_la-tame.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-tame.lo
	-rm -f itu/g.723.1a/codec_g723_la-util_cng.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-util_cng.lo
	-rm -f itu/g.723.1a/codec_g723_la-util_lbc.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-util_lbc.lo
	-rm -f itu/g.723.1a/codec_g723_la-vad.$(OBJEXT)
	-rm -f itu/g.723.1a/codec_g723_la-vad.lo
	-rm -f itu/g.729a/codec_g729_la-acelp_ca.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-acelp_ca.lo
	-rm -f itu/g.729a/codec_g729_la-basic_op.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-basic_op.lo
	-rm -f itu/g.729a/codec_g729_la-cod_ld8a.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-cod_ld8a.lo
	-rm -f itu/g.729a/codec_g729_la-cor_func.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-cor_func.lo
	-rm -f itu/g.729a/codec_g729_la-de_acelp.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-de_acelp.lo
	-rm -f itu/g.729a/codec_g729_la-dec_gain.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-dec_gain.lo
	-rm -f itu/g.729a/codec_g729_la-dec_lag3.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-dec_lag3.lo
	-rm -f itu/g.729a/codec_g729_la-dec_ld8a.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-dec_ld8a.lo
	-rm -f itu/g.729a/codec_g729_la-dspfunc.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-dspfunc.lo
	-rm -f itu/g.729a/codec_g729_la-filter.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-filter.lo
	-rm -f itu/g.729a/codec_g729_la-gainpred.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-gainpred.lo
	-rm -f itu/g.729a/codec_g729_la-lpc.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-lpc.lo
	-rm -f itu/g.729a/codec_g729_la-lpcfunc.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-lpcfunc.lo
	-rm -f itu/g.729a/codec_g729_la-lspdec.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-lspdec.lo
	-rm -f itu/g.729a/codec_g729_la-lspgetq.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-lspgetq.lo
	-rm -f itu/g.729a/codec_g729_la-oper_32b.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-oper_32b.lo
	-rm -f itu/g.729a/codec_g729_la-p_parity.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-p_parity.lo
	-rm -f itu/g.729a/codec_g729_la-pitch_a.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-pitch_a.lo
	-rm -f itu/g.729a/codec_g729_la-post_pro.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-post_pro.lo
	-rm -f itu/g.729a/codec_g729_la-postfilt.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-postfilt.lo
	-rm -f itu/g.729a/codec_g729_la-pre_proc.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-pre_proc.lo
	-rm -f itu/g.729a/codec_g729_la-pred_lt3.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-pred_lt3.lo
	-rm -f itu/g.729a/codec_g729_la-qua_gain.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-qua_gain.lo
	-rm -f itu/g.729a/codec_g729_la-qua_lsp.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-qua_lsp.lo
	-rm -f itu/g.729a/codec_g729_la-tab_ld8a.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-tab_ld8a.lo
	-rm -f itu/g.729a/codec_g729_la-taming.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-taming.lo
	-rm -f itu/g.729a/codec_g729_la-util.$(OBJEXT)
	-rm -f itu/g.729a/codec_g729_la-util.lo

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/codec_g723_la-codec_g72x.Plo
include ./$(DEPDIR)/codec_g729_la-codec_g72x.Plo
include ./$(DEPDIR)/codec_g729nofp_la-codec_g72x.Plo
include ipp/$(DEPDIR)/codec_g723_la-aux_tbls.Plo
include ipp/$(DEPDIR)/codec_g723_la-decg723.Plo
include ipp/$(DEPDIR)/codec_g723_la-encg723.Plo
include ipp/$(DEPDIR)/codec_g723_la-owng723.Plo
include ipp/$(DEPDIR)/codec_g723_la-vadg723.Plo
include ipp/$(DEPDIR)/codec_g729_la-decg729fp.Plo
include ipp/$(DEPDIR)/codec_g729_la-encg729fp.Plo
include ipp/$(DEPDIR)/codec_g729_la-owng729fp.Plo
include ipp/$(DEPDIR)/codec_g729_la-vadg729fp.Plo
include ipp/$(DEPDIR)/codec_g729nofp_la-aux_tbls.Plo
include ipp/$(DEPDIR)/codec_g729nofp_la-decg729.Plo
include ipp/$(DEPDIR)/codec_g729nofp_la-encg729.Plo
include ipp/$(DEPDIR)/codec_g729nofp_la-owng729.Plo
include ipp/$(DEPDIR)/codec_g729nofp_la-vadg729.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-basop.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-cod_cng.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-coder.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-dec_cng.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-decod.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-exc_lbc.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-lpc.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-lsp.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-tab_lbc.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-tame.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-util_cng.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-util_lbc.Plo
include itu/g.723.1a/$(DEPDIR)/codec_g723_la-vad.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-acelp_ca.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-basic_op.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-cod_ld8a.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-cor_func.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-de_acelp.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-dec_gain.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-dec_lag3.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-dec_ld8a.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-dspfunc.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-filter.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-gainpred.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-lpc.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-lpcfunc.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-lspdec.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-lspgetq.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-oper_32b.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-p_parity.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-pitch_a.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-post_pro.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-postfilt.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-pre_proc.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-pred_lt3.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-qua_gain.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-qua_lsp.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-tab_ld8a.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-taming.Plo
include itu/g.729a/$(DEPDIR)/codec_g729_la-util.Plo

.c.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	mv -f $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ $<

.c.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	mv -f $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	mv -f $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

codec_g723_la-codec_g72x.lo: codec_g72x.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT codec_g723_la-codec_g72x.lo -MD -MP -MF $(DEPDIR)/codec_g723_la-codec_g72x.Tpo -c -o codec_g723_la-codec_g72x.lo `test -f 'codec_g72x.c' || echo '$(srcdir)/'`codec_g72x.c
	mv -f $(DEPDIR)/codec_g723_la-codec_g72x.Tpo $(DEPDIR)/codec_g723_la-codec_g72x.Plo
#	source='codec_g72x.c' object='codec_g723_la-codec_g72x.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o codec_g723_la-codec_g72x.lo `test -f 'codec_g72x.c' || echo '$(srcdir)/'`codec_g72x.c

ipp/codec_g723_la-decg723.lo: ipp/decg723.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g723_la-decg723.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g723_la-decg723.Tpo -c -o ipp/codec_g723_la-decg723.lo `test -f 'ipp/decg723.c' || echo '$(srcdir)/'`ipp/decg723.c
	mv -f ipp/$(DEPDIR)/codec_g723_la-decg723.Tpo ipp/$(DEPDIR)/codec_g723_la-decg723.Plo
#	source='ipp/decg723.c' object='ipp/codec_g723_la-decg723.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g723_la-decg723.lo `test -f 'ipp/decg723.c' || echo '$(srcdir)/'`ipp/decg723.c

ipp/codec_g723_la-encg723.lo: ipp/encg723.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g723_la-encg723.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g723_la-encg723.Tpo -c -o ipp/codec_g723_la-encg723.lo `test -f 'ipp/encg723.c' || echo '$(srcdir)/'`ipp/encg723.c
	mv -f ipp/$(DEPDIR)/codec_g723_la-encg723.Tpo ipp/$(DEPDIR)/codec_g723_la-encg723.Plo
#	source='ipp/encg723.c' object='ipp/codec_g723_la-encg723.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g723_la-encg723.lo `test -f 'ipp/encg723.c' || echo '$(srcdir)/'`ipp/encg723.c

ipp/codec_g723_la-owng723.lo: ipp/owng723.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g723_la-owng723.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g723_la-owng723.Tpo -c -o ipp/codec_g723_la-owng723.lo `test -f 'ipp/owng723.c' || echo '$(srcdir)/'`ipp/owng723.c
	mv -f ipp/$(DEPDIR)/codec_g723_la-owng723.Tpo ipp/$(DEPDIR)/codec_g723_la-owng723.Plo
#	source='ipp/owng723.c' object='ipp/codec_g723_la-owng723.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g723_la-owng723.lo `test -f 'ipp/owng723.c' || echo '$(srcdir)/'`ipp/owng723.c

ipp/codec_g723_la-vadg723.lo: ipp/vadg723.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g723_la-vadg723.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g723_la-vadg723.Tpo -c -o ipp/codec_g723_la-vadg723.lo `test -f 'ipp/vadg723.c' || echo '$(srcdir)/'`ipp/vadg723.c
	mv -f ipp/$(DEPDIR)/codec_g723_la-vadg723.Tpo ipp/$(DEPDIR)/codec_g723_la-vadg723.Plo
#	source='ipp/vadg723.c' object='ipp/codec_g723_la-vadg723.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g723_la-vadg723.lo `test -f 'ipp/vadg723.c' || echo '$(srcdir)/'`ipp/vadg723.c

ipp/codec_g723_la-aux_tbls.lo: ipp/aux_tbls.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g723_la-aux_tbls.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g723_la-aux_tbls.Tpo -c -o ipp/codec_g723_la-aux_tbls.lo `test -f 'ipp/aux_tbls.c' || echo '$(srcdir)/'`ipp/aux_tbls.c
	mv -f ipp/$(DEPDIR)/codec_g723_la-aux_tbls.Tpo ipp/$(DEPDIR)/codec_g723_la-aux_tbls.Plo
#	source='ipp/aux_tbls.c' object='ipp/codec_g723_la-aux_tbls.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g723_la-aux_tbls.lo `test -f 'ipp/aux_tbls.c' || echo '$(srcdir)/'`ipp/aux_tbls.c

itu/g.723.1a/codec_g723_la-basop.lo: itu/g.723.1a/basop.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-basop.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-basop.Tpo -c -o itu/g.723.1a/codec_g723_la-basop.lo `test -f 'itu/g.723.1a/basop.c' || echo '$(srcdir)/'`itu/g.723.1a/basop.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-basop.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-basop.Plo
#	source='itu/g.723.1a/basop.c' object='itu/g.723.1a/codec_g723_la-basop.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-basop.lo `test -f 'itu/g.723.1a/basop.c' || echo '$(srcdir)/'`itu/g.723.1a/basop.c

itu/g.723.1a/codec_g723_la-cod_cng.lo: itu/g.723.1a/cod_cng.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-cod_cng.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-cod_cng.Tpo -c -o itu/g.723.1a/codec_g723_la-cod_cng.lo `test -f 'itu/g.723.1a/cod_cng.c' || echo '$(srcdir)/'`itu/g.723.1a/cod_cng.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-cod_cng.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-cod_cng.Plo
#	source='itu/g.723.1a/cod_cng.c' object='itu/g.723.1a/codec_g723_la-cod_cng.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-cod_cng.lo `test -f 'itu/g.723.1a/cod_cng.c' || echo '$(srcdir)/'`itu/g.723.1a/cod_cng.c

itu/g.723.1a/codec_g723_la-coder.lo: itu/g.723.1a/coder.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-coder.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-coder.Tpo -c -o itu/g.723.1a/codec_g723_la-coder.lo `test -f 'itu/g.723.1a/coder.c' || echo '$(srcdir)/'`itu/g.723.1a/coder.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-coder.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-coder.Plo
#	source='itu/g.723.1a/coder.c' object='itu/g.723.1a/codec_g723_la-coder.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-coder.lo `test -f 'itu/g.723.1a/coder.c' || echo '$(srcdir)/'`itu/g.723.1a/coder.c

itu/g.723.1a/codec_g723_la-dec_cng.lo: itu/g.723.1a/dec_cng.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-dec_cng.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-dec_cng.Tpo -c -o itu/g.723.1a/codec_g723_la-dec_cng.lo `test -f 'itu/g.723.1a/dec_cng.c' || echo '$(srcdir)/'`itu/g.723.1a/dec_cng.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-dec_cng.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-dec_cng.Plo
#	source='itu/g.723.1a/dec_cng.c' object='itu/g.723.1a/codec_g723_la-dec_cng.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-dec_cng.lo `test -f 'itu/g.723.1a/dec_cng.c' || echo '$(srcdir)/'`itu/g.723.1a/dec_cng.c

itu/g.723.1a/codec_g723_la-decod.lo: itu/g.723.1a/decod.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-decod.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-decod.Tpo -c -o itu/g.723.1a/codec_g723_la-decod.lo `test -f 'itu/g.723.1a/decod.c' || echo '$(srcdir)/'`itu/g.723.1a/decod.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-decod.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-decod.Plo
#	source='itu/g.723.1a/decod.c' object='itu/g.723.1a/codec_g723_la-decod.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-decod.lo `test -f 'itu/g.723.1a/decod.c' || echo '$(srcdir)/'`itu/g.723.1a/decod.c

itu/g.723.1a/codec_g723_la-exc_lbc.lo: itu/g.723.1a/exc_lbc.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-exc_lbc.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-exc_lbc.Tpo -c -o itu/g.723.1a/codec_g723_la-exc_lbc.lo `test -f 'itu/g.723.1a/exc_lbc.c' || echo '$(srcdir)/'`itu/g.723.1a/exc_lbc.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-exc_lbc.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-exc_lbc.Plo
#	source='itu/g.723.1a/exc_lbc.c' object='itu/g.723.1a/codec_g723_la-exc_lbc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-exc_lbc.lo `test -f 'itu/g.723.1a/exc_lbc.c' || echo '$(srcdir)/'`itu/g.723.1a/exc_lbc.c

itu/g.723.1a/codec_g723_la-lpc.lo: itu/g.723.1a/lpc.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-lpc.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-lpc.Tpo -c -o itu/g.723.1a/codec_g723_la-lpc.lo `test -f 'itu/g.723.1a/lpc.c' || echo '$(srcdir)/'`itu/g.723.1a/lpc.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-lpc.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-lpc.Plo
#	source='itu/g.723.1a/lpc.c' object='itu/g.723.1a/codec_g723_la-lpc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-lpc.lo `test -f 'itu/g.723.1a/lpc.c' || echo '$(srcdir)/'`itu/g.723.1a/lpc.c

itu/g.723.1a/codec_g723_la-lsp.lo: itu/g.723.1a/lsp.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-lsp.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-lsp.Tpo -c -o itu/g.723.1a/codec_g723_la-lsp.lo `test -f 'itu/g.723.1a/lsp.c' || echo '$(srcdir)/'`itu/g.723.1a/lsp.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-lsp.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-lsp.Plo
#	source='itu/g.723.1a/lsp.c' object='itu/g.723.1a/codec_g723_la-lsp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-lsp.lo `test -f 'itu/g.723.1a/lsp.c' || echo '$(srcdir)/'`itu/g.723.1a/lsp.c

itu/g.723.1a/codec_g723_la-tab_lbc.lo: itu/g.723.1a/tab_lbc.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-tab_lbc.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-tab_lbc.Tpo -c -o itu/g.723.1a/codec_g723_la-tab_lbc.lo `test -f 'itu/g.723.1a/tab_lbc.c' || echo '$(srcdir)/'`itu/g.723.1a/tab_lbc.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-tab_lbc.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-tab_lbc.Plo
#	source='itu/g.723.1a/tab_lbc.c' object='itu/g.723.1a/codec_g723_la-tab_lbc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-tab_lbc.lo `test -f 'itu/g.723.1a/tab_lbc.c' || echo '$(srcdir)/'`itu/g.723.1a/tab_lbc.c

itu/g.723.1a/codec_g723_la-tame.lo: itu/g.723.1a/tame.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-tame.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-tame.Tpo -c -o itu/g.723.1a/codec_g723_la-tame.lo `test -f 'itu/g.723.1a/tame.c' || echo '$(srcdir)/'`itu/g.723.1a/tame.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-tame.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-tame.Plo
#	source='itu/g.723.1a/tame.c' object='itu/g.723.1a/codec_g723_la-tame.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-tame.lo `test -f 'itu/g.723.1a/tame.c' || echo '$(srcdir)/'`itu/g.723.1a/tame.c

itu/g.723.1a/codec_g723_la-util_cng.lo: itu/g.723.1a/util_cng.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-util_cng.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-util_cng.Tpo -c -o itu/g.723.1a/codec_g723_la-util_cng.lo `test -f 'itu/g.723.1a/util_cng.c' || echo '$(srcdir)/'`itu/g.723.1a/util_cng.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-util_cng.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-util_cng.Plo
#	source='itu/g.723.1a/util_cng.c' object='itu/g.723.1a/codec_g723_la-util_cng.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-util_cng.lo `test -f 'itu/g.723.1a/util_cng.c' || echo '$(srcdir)/'`itu/g.723.1a/util_cng.c

itu/g.723.1a/codec_g723_la-util_lbc.lo: itu/g.723.1a/util_lbc.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-util_lbc.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-util_lbc.Tpo -c -o itu/g.723.1a/codec_g723_la-util_lbc.lo `test -f 'itu/g.723.1a/util_lbc.c' || echo '$(srcdir)/'`itu/g.723.1a/util_lbc.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-util_lbc.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-util_lbc.Plo
#	source='itu/g.723.1a/util_lbc.c' object='itu/g.723.1a/codec_g723_la-util_lbc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-util_lbc.lo `test -f 'itu/g.723.1a/util_lbc.c' || echo '$(srcdir)/'`itu/g.723.1a/util_lbc.c

itu/g.723.1a/codec_g723_la-vad.lo: itu/g.723.1a/vad.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -MT itu/g.723.1a/codec_g723_la-vad.lo -MD -MP -MF itu/g.723.1a/$(DEPDIR)/codec_g723_la-vad.Tpo -c -o itu/g.723.1a/codec_g723_la-vad.lo `test -f 'itu/g.723.1a/vad.c' || echo '$(srcdir)/'`itu/g.723.1a/vad.c
	mv -f itu/g.723.1a/$(DEPDIR)/codec_g723_la-vad.Tpo itu/g.723.1a/$(DEPDIR)/codec_g723_la-vad.Plo
#	source='itu/g.723.1a/vad.c' object='itu/g.723.1a/codec_g723_la-vad.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g723_la_CFLAGS) $(CFLAGS) -c -o itu/g.723.1a/codec_g723_la-vad.lo `test -f 'itu/g.723.1a/vad.c' || echo '$(srcdir)/'`itu/g.723.1a/vad.c

codec_g729_la-codec_g72x.lo: codec_g72x.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT codec_g729_la-codec_g72x.lo -MD -MP -MF $(DEPDIR)/codec_g729_la-codec_g72x.Tpo -c -o codec_g729_la-codec_g72x.lo `test -f 'codec_g72x.c' || echo '$(srcdir)/'`codec_g72x.c
	mv -f $(DEPDIR)/codec_g729_la-codec_g72x.Tpo $(DEPDIR)/codec_g729_la-codec_g72x.Plo
#	source='codec_g72x.c' object='codec_g729_la-codec_g72x.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o codec_g729_la-codec_g72x.lo `test -f 'codec_g72x.c' || echo '$(srcdir)/'`codec_g72x.c

ipp/codec_g729_la-decg729fp.lo: ipp/decg729fp.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729_la-decg729fp.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729_la-decg729fp.Tpo -c -o ipp/codec_g729_la-decg729fp.lo `test -f 'ipp/decg729fp.c' || echo '$(srcdir)/'`ipp/decg729fp.c
	mv -f ipp/$(DEPDIR)/codec_g729_la-decg729fp.Tpo ipp/$(DEPDIR)/codec_g729_la-decg729fp.Plo
#	source='ipp/decg729fp.c' object='ipp/codec_g729_la-decg729fp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729_la-decg729fp.lo `test -f 'ipp/decg729fp.c' || echo '$(srcdir)/'`ipp/decg729fp.c

ipp/codec_g729_la-encg729fp.lo: ipp/encg729fp.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729_la-encg729fp.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729_la-encg729fp.Tpo -c -o ipp/codec_g729_la-encg729fp.lo `test -f 'ipp/encg729fp.c' || echo '$(srcdir)/'`ipp/encg729fp.c
	mv -f ipp/$(DEPDIR)/codec_g729_la-encg729fp.Tpo ipp/$(DEPDIR)/codec_g729_la-encg729fp.Plo
#	source='ipp/encg729fp.c' object='ipp/codec_g729_la-encg729fp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729_la-encg729fp.lo `test -f 'ipp/encg729fp.c' || echo '$(srcdir)/'`ipp/encg729fp.c

ipp/codec_g729_la-owng729fp.lo: ipp/owng729fp.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729_la-owng729fp.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729_la-owng729fp.Tpo -c -o ipp/codec_g729_la-owng729fp.lo `test -f 'ipp/owng729fp.c' || echo '$(srcdir)/'`ipp/owng729fp.c
	mv -f ipp/$(DEPDIR)/codec_g729_la-owng729fp.Tpo ipp/$(DEPDIR)/codec_g729_la-owng729fp.Plo
#	source='ipp/owng729fp.c' object='ipp/codec_g729_la-owng729fp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729_la-owng729fp.lo `test -f 'ipp/owng729fp.c' || echo '$(srcdir)/'`ipp/owng729fp.c

ipp/codec_g729_la-vadg729fp.lo: ipp/vadg729fp.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729_la-vadg729fp.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729_la-vadg729fp.Tpo -c -o ipp/codec_g729_la-vadg729fp.lo `test -f 'ipp/vadg729fp.c' || echo '$(srcdir)/'`ipp/vadg729fp.c
	mv -f ipp/$(DEPDIR)/codec_g729_la-vadg729fp.Tpo ipp/$(DEPDIR)/codec_g729_la-vadg729fp.Plo
#	source='ipp/vadg729fp.c' object='ipp/codec_g729_la-vadg729fp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729_la-vadg729fp.lo `test -f 'ipp/vadg729fp.c' || echo '$(srcdir)/'`ipp/vadg729fp.c

itu/g.729a/codec_g729_la-acelp_ca.lo: itu/g.729a/acelp_ca.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-acelp_ca.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-acelp_ca.Tpo -c -o itu/g.729a/codec_g729_la-acelp_ca.lo `test -f 'itu/g.729a/acelp_ca.c' || echo '$(srcdir)/'`itu/g.729a/acelp_ca.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-acelp_ca.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-acelp_ca.Plo
#	source='itu/g.729a/acelp_ca.c' object='itu/g.729a/codec_g729_la-acelp_ca.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-acelp_ca.lo `test -f 'itu/g.729a/acelp_ca.c' || echo '$(srcdir)/'`itu/g.729a/acelp_ca.c

itu/g.729a/codec_g729_la-basic_op.lo: itu/g.729a/basic_op.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-basic_op.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-basic_op.Tpo -c -o itu/g.729a/codec_g729_la-basic_op.lo `test -f 'itu/g.729a/basic_op.c' || echo '$(srcdir)/'`itu/g.729a/basic_op.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-basic_op.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-basic_op.Plo
#	source='itu/g.729a/basic_op.c' object='itu/g.729a/codec_g729_la-basic_op.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-basic_op.lo `test -f 'itu/g.729a/basic_op.c' || echo '$(srcdir)/'`itu/g.729a/basic_op.c

itu/g.729a/codec_g729_la-cod_ld8a.lo: itu/g.729a/cod_ld8a.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-cod_ld8a.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-cod_ld8a.Tpo -c -o itu/g.729a/codec_g729_la-cod_ld8a.lo `test -f 'itu/g.729a/cod_ld8a.c' || echo '$(srcdir)/'`itu/g.729a/cod_ld8a.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-cod_ld8a.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-cod_ld8a.Plo
#	source='itu/g.729a/cod_ld8a.c' object='itu/g.729a/codec_g729_la-cod_ld8a.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-cod_ld8a.lo `test -f 'itu/g.729a/cod_ld8a.c' || echo '$(srcdir)/'`itu/g.729a/cod_ld8a.c

itu/g.729a/codec_g729_la-cor_func.lo: itu/g.729a/cor_func.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-cor_func.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-cor_func.Tpo -c -o itu/g.729a/codec_g729_la-cor_func.lo `test -f 'itu/g.729a/cor_func.c' || echo '$(srcdir)/'`itu/g.729a/cor_func.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-cor_func.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-cor_func.Plo
#	source='itu/g.729a/cor_func.c' object='itu/g.729a/codec_g729_la-cor_func.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-cor_func.lo `test -f 'itu/g.729a/cor_func.c' || echo '$(srcdir)/'`itu/g.729a/cor_func.c

itu/g.729a/codec_g729_la-de_acelp.lo: itu/g.729a/de_acelp.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-de_acelp.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-de_acelp.Tpo -c -o itu/g.729a/codec_g729_la-de_acelp.lo `test -f 'itu/g.729a/de_acelp.c' || echo '$(srcdir)/'`itu/g.729a/de_acelp.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-de_acelp.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-de_acelp.Plo
#	source='itu/g.729a/de_acelp.c' object='itu/g.729a/codec_g729_la-de_acelp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-de_acelp.lo `test -f 'itu/g.729a/de_acelp.c' || echo '$(srcdir)/'`itu/g.729a/de_acelp.c

itu/g.729a/codec_g729_la-dec_gain.lo: itu/g.729a/dec_gain.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-dec_gain.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-dec_gain.Tpo -c -o itu/g.729a/codec_g729_la-dec_gain.lo `test -f 'itu/g.729a/dec_gain.c' || echo '$(srcdir)/'`itu/g.729a/dec_gain.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-dec_gain.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-dec_gain.Plo
#	source='itu/g.729a/dec_gain.c' object='itu/g.729a/codec_g729_la-dec_gain.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-dec_gain.lo `test -f 'itu/g.729a/dec_gain.c' || echo '$(srcdir)/'`itu/g.729a/dec_gain.c

itu/g.729a/codec_g729_la-dec_lag3.lo: itu/g.729a/dec_lag3.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-dec_lag3.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-dec_lag3.Tpo -c -o itu/g.729a/codec_g729_la-dec_lag3.lo `test -f 'itu/g.729a/dec_lag3.c' || echo '$(srcdir)/'`itu/g.729a/dec_lag3.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-dec_lag3.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-dec_lag3.Plo
#	source='itu/g.729a/dec_lag3.c' object='itu/g.729a/codec_g729_la-dec_lag3.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-dec_lag3.lo `test -f 'itu/g.729a/dec_lag3.c' || echo '$(srcdir)/'`itu/g.729a/dec_lag3.c

itu/g.729a/codec_g729_la-dec_ld8a.lo: itu/g.729a/dec_ld8a.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-dec_ld8a.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-dec_ld8a.Tpo -c -o itu/g.729a/codec_g729_la-dec_ld8a.lo `test -f 'itu/g.729a/dec_ld8a.c' || echo '$(srcdir)/'`itu/g.729a/dec_ld8a.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-dec_ld8a.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-dec_ld8a.Plo
#	source='itu/g.729a/dec_ld8a.c' object='itu/g.729a/codec_g729_la-dec_ld8a.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-dec_ld8a.lo `test -f 'itu/g.729a/dec_ld8a.c' || echo '$(srcdir)/'`itu/g.729a/dec_ld8a.c

itu/g.729a/codec_g729_la-dspfunc.lo: itu/g.729a/dspfunc.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-dspfunc.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-dspfunc.Tpo -c -o itu/g.729a/codec_g729_la-dspfunc.lo `test -f 'itu/g.729a/dspfunc.c' || echo '$(srcdir)/'`itu/g.729a/dspfunc.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-dspfunc.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-dspfunc.Plo
#	source='itu/g.729a/dspfunc.c' object='itu/g.729a/codec_g729_la-dspfunc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-dspfunc.lo `test -f 'itu/g.729a/dspfunc.c' || echo '$(srcdir)/'`itu/g.729a/dspfunc.c

itu/g.729a/codec_g729_la-filter.lo: itu/g.729a/filter.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-filter.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-filter.Tpo -c -o itu/g.729a/codec_g729_la-filter.lo `test -f 'itu/g.729a/filter.c' || echo '$(srcdir)/'`itu/g.729a/filter.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-filter.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-filter.Plo
#	source='itu/g.729a/filter.c' object='itu/g.729a/codec_g729_la-filter.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-filter.lo `test -f 'itu/g.729a/filter.c' || echo '$(srcdir)/'`itu/g.729a/filter.c

itu/g.729a/codec_g729_la-gainpred.lo: itu/g.729a/gainpred.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-gainpred.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-gainpred.Tpo -c -o itu/g.729a/codec_g729_la-gainpred.lo `test -f 'itu/g.729a/gainpred.c' || echo '$(srcdir)/'`itu/g.729a/gainpred.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-gainpred.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-gainpred.Plo
#	source='itu/g.729a/gainpred.c' object='itu/g.729a/codec_g729_la-gainpred.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-gainpred.lo `test -f 'itu/g.729a/gainpred.c' || echo '$(srcdir)/'`itu/g.729a/gainpred.c

itu/g.729a/codec_g729_la-lpc.lo: itu/g.729a/lpc.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-lpc.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-lpc.Tpo -c -o itu/g.729a/codec_g729_la-lpc.lo `test -f 'itu/g.729a/lpc.c' || echo '$(srcdir)/'`itu/g.729a/lpc.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-lpc.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-lpc.Plo
#	source='itu/g.729a/lpc.c' object='itu/g.729a/codec_g729_la-lpc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-lpc.lo `test -f 'itu/g.729a/lpc.c' || echo '$(srcdir)/'`itu/g.729a/lpc.c

itu/g.729a/codec_g729_la-lpcfunc.lo: itu/g.729a/lpcfunc.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-lpcfunc.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-lpcfunc.Tpo -c -o itu/g.729a/codec_g729_la-lpcfunc.lo `test -f 'itu/g.729a/lpcfunc.c' || echo '$(srcdir)/'`itu/g.729a/lpcfunc.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-lpcfunc.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-lpcfunc.Plo
#	source='itu/g.729a/lpcfunc.c' object='itu/g.729a/codec_g729_la-lpcfunc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-lpcfunc.lo `test -f 'itu/g.729a/lpcfunc.c' || echo '$(srcdir)/'`itu/g.729a/lpcfunc.c

itu/g.729a/codec_g729_la-lspdec.lo: itu/g.729a/lspdec.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-lspdec.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-lspdec.Tpo -c -o itu/g.729a/codec_g729_la-lspdec.lo `test -f 'itu/g.729a/lspdec.c' || echo '$(srcdir)/'`itu/g.729a/lspdec.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-lspdec.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-lspdec.Plo
#	source='itu/g.729a/lspdec.c' object='itu/g.729a/codec_g729_la-lspdec.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-lspdec.lo `test -f 'itu/g.729a/lspdec.c' || echo '$(srcdir)/'`itu/g.729a/lspdec.c

itu/g.729a/codec_g729_la-lspgetq.lo: itu/g.729a/lspgetq.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-lspgetq.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-lspgetq.Tpo -c -o itu/g.729a/codec_g729_la-lspgetq.lo `test -f 'itu/g.729a/lspgetq.c' || echo '$(srcdir)/'`itu/g.729a/lspgetq.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-lspgetq.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-lspgetq.Plo
#	source='itu/g.729a/lspgetq.c' object='itu/g.729a/codec_g729_la-lspgetq.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-lspgetq.lo `test -f 'itu/g.729a/lspgetq.c' || echo '$(srcdir)/'`itu/g.729a/lspgetq.c

itu/g.729a/codec_g729_la-oper_32b.lo: itu/g.729a/oper_32b.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-oper_32b.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-oper_32b.Tpo -c -o itu/g.729a/codec_g729_la-oper_32b.lo `test -f 'itu/g.729a/oper_32b.c' || echo '$(srcdir)/'`itu/g.729a/oper_32b.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-oper_32b.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-oper_32b.Plo
#	source='itu/g.729a/oper_32b.c' object='itu/g.729a/codec_g729_la-oper_32b.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-oper_32b.lo `test -f 'itu/g.729a/oper_32b.c' || echo '$(srcdir)/'`itu/g.729a/oper_32b.c

itu/g.729a/codec_g729_la-p_parity.lo: itu/g.729a/p_parity.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-p_parity.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-p_parity.Tpo -c -o itu/g.729a/codec_g729_la-p_parity.lo `test -f 'itu/g.729a/p_parity.c' || echo '$(srcdir)/'`itu/g.729a/p_parity.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-p_parity.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-p_parity.Plo
#	source='itu/g.729a/p_parity.c' object='itu/g.729a/codec_g729_la-p_parity.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-p_parity.lo `test -f 'itu/g.729a/p_parity.c' || echo '$(srcdir)/'`itu/g.729a/p_parity.c

itu/g.729a/codec_g729_la-pitch_a.lo: itu/g.729a/pitch_a.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-pitch_a.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-pitch_a.Tpo -c -o itu/g.729a/codec_g729_la-pitch_a.lo `test -f 'itu/g.729a/pitch_a.c' || echo '$(srcdir)/'`itu/g.729a/pitch_a.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-pitch_a.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-pitch_a.Plo
#	source='itu/g.729a/pitch_a.c' object='itu/g.729a/codec_g729_la-pitch_a.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-pitch_a.lo `test -f 'itu/g.729a/pitch_a.c' || echo '$(srcdir)/'`itu/g.729a/pitch_a.c

itu/g.729a/codec_g729_la-post_pro.lo: itu/g.729a/post_pro.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-post_pro.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-post_pro.Tpo -c -o itu/g.729a/codec_g729_la-post_pro.lo `test -f 'itu/g.729a/post_pro.c' || echo '$(srcdir)/'`itu/g.729a/post_pro.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-post_pro.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-post_pro.Plo
#	source='itu/g.729a/post_pro.c' object='itu/g.729a/codec_g729_la-post_pro.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-post_pro.lo `test -f 'itu/g.729a/post_pro.c' || echo '$(srcdir)/'`itu/g.729a/post_pro.c

itu/g.729a/codec_g729_la-postfilt.lo: itu/g.729a/postfilt.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-postfilt.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-postfilt.Tpo -c -o itu/g.729a/codec_g729_la-postfilt.lo `test -f 'itu/g.729a/postfilt.c' || echo '$(srcdir)/'`itu/g.729a/postfilt.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-postfilt.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-postfilt.Plo
#	source='itu/g.729a/postfilt.c' object='itu/g.729a/codec_g729_la-postfilt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-postfilt.lo `test -f 'itu/g.729a/postfilt.c' || echo '$(srcdir)/'`itu/g.729a/postfilt.c

itu/g.729a/codec_g729_la-pre_proc.lo: itu/g.729a/pre_proc.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-pre_proc.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-pre_proc.Tpo -c -o itu/g.729a/codec_g729_la-pre_proc.lo `test -f 'itu/g.729a/pre_proc.c' || echo '$(srcdir)/'`itu/g.729a/pre_proc.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-pre_proc.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-pre_proc.Plo
#	source='itu/g.729a/pre_proc.c' object='itu/g.729a/codec_g729_la-pre_proc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-pre_proc.lo `test -f 'itu/g.729a/pre_proc.c' || echo '$(srcdir)/'`itu/g.729a/pre_proc.c

itu/g.729a/codec_g729_la-pred_lt3.lo: itu/g.729a/pred_lt3.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-pred_lt3.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-pred_lt3.Tpo -c -o itu/g.729a/codec_g729_la-pred_lt3.lo `test -f 'itu/g.729a/pred_lt3.c' || echo '$(srcdir)/'`itu/g.729a/pred_lt3.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-pred_lt3.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-pred_lt3.Plo
#	source='itu/g.729a/pred_lt3.c' object='itu/g.729a/codec_g729_la-pred_lt3.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-pred_lt3.lo `test -f 'itu/g.729a/pred_lt3.c' || echo '$(srcdir)/'`itu/g.729a/pred_lt3.c

itu/g.729a/codec_g729_la-qua_gain.lo: itu/g.729a/qua_gain.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-qua_gain.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-qua_gain.Tpo -c -o itu/g.729a/codec_g729_la-qua_gain.lo `test -f 'itu/g.729a/qua_gain.c' || echo '$(srcdir)/'`itu/g.729a/qua_gain.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-qua_gain.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-qua_gain.Plo
#	source='itu/g.729a/qua_gain.c' object='itu/g.729a/codec_g729_la-qua_gain.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-qua_gain.lo `test -f 'itu/g.729a/qua_gain.c' || echo '$(srcdir)/'`itu/g.729a/qua_gain.c

itu/g.729a/codec_g729_la-qua_lsp.lo: itu/g.729a/qua_lsp.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-qua_lsp.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-qua_lsp.Tpo -c -o itu/g.729a/codec_g729_la-qua_lsp.lo `test -f 'itu/g.729a/qua_lsp.c' || echo '$(srcdir)/'`itu/g.729a/qua_lsp.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-qua_lsp.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-qua_lsp.Plo
#	source='itu/g.729a/qua_lsp.c' object='itu/g.729a/codec_g729_la-qua_lsp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-qua_lsp.lo `test -f 'itu/g.729a/qua_lsp.c' || echo '$(srcdir)/'`itu/g.729a/qua_lsp.c

itu/g.729a/codec_g729_la-tab_ld8a.lo: itu/g.729a/tab_ld8a.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-tab_ld8a.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-tab_ld8a.Tpo -c -o itu/g.729a/codec_g729_la-tab_ld8a.lo `test -f 'itu/g.729a/tab_ld8a.c' || echo '$(srcdir)/'`itu/g.729a/tab_ld8a.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-tab_ld8a.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-tab_ld8a.Plo
#	source='itu/g.729a/tab_ld8a.c' object='itu/g.729a/codec_g729_la-tab_ld8a.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-tab_ld8a.lo `test -f 'itu/g.729a/tab_ld8a.c' || echo '$(srcdir)/'`itu/g.729a/tab_ld8a.c

itu/g.729a/codec_g729_la-taming.lo: itu/g.729a/taming.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-taming.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-taming.Tpo -c -o itu/g.729a/codec_g729_la-taming.lo `test -f 'itu/g.729a/taming.c' || echo '$(srcdir)/'`itu/g.729a/taming.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-taming.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-taming.Plo
#	source='itu/g.729a/taming.c' object='itu/g.729a/codec_g729_la-taming.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-taming.lo `test -f 'itu/g.729a/taming.c' || echo '$(srcdir)/'`itu/g.729a/taming.c

itu/g.729a/codec_g729_la-util.lo: itu/g.729a/util.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -MT itu/g.729a/codec_g729_la-util.lo -MD -MP -MF itu/g.729a/$(DEPDIR)/codec_g729_la-util.Tpo -c -o itu/g.729a/codec_g729_la-util.lo `test -f 'itu/g.729a/util.c' || echo '$(srcdir)/'`itu/g.729a/util.c
	mv -f itu/g.729a/$(DEPDIR)/codec_g729_la-util.Tpo itu/g.729a/$(DEPDIR)/codec_g729_la-util.Plo
#	source='itu/g.729a/util.c' object='itu/g.729a/codec_g729_la-util.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729_la_CFLAGS) $(CFLAGS) -c -o itu/g.729a/codec_g729_la-util.lo `test -f 'itu/g.729a/util.c' || echo '$(srcdir)/'`itu/g.729a/util.c

codec_g729nofp_la-codec_g72x.lo: codec_g72x.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -MT codec_g729nofp_la-codec_g72x.lo -MD -MP -MF $(DEPDIR)/codec_g729nofp_la-codec_g72x.Tpo -c -o codec_g729nofp_la-codec_g72x.lo `test -f 'codec_g72x.c' || echo '$(srcdir)/'`codec_g72x.c
	mv -f $(DEPDIR)/codec_g729nofp_la-codec_g72x.Tpo $(DEPDIR)/codec_g729nofp_la-codec_g72x.Plo
#	source='codec_g72x.c' object='codec_g729nofp_la-codec_g72x.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -c -o codec_g729nofp_la-codec_g72x.lo `test -f 'codec_g72x.c' || echo '$(srcdir)/'`codec_g72x.c

ipp/codec_g729nofp_la-decg729.lo: ipp/decg729.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729nofp_la-decg729.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729nofp_la-decg729.Tpo -c -o ipp/codec_g729nofp_la-decg729.lo `test -f 'ipp/decg729.c' || echo '$(srcdir)/'`ipp/decg729.c
	mv -f ipp/$(DEPDIR)/codec_g729nofp_la-decg729.Tpo ipp/$(DEPDIR)/codec_g729nofp_la-decg729.Plo
#	source='ipp/decg729.c' object='ipp/codec_g729nofp_la-decg729.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729nofp_la-decg729.lo `test -f 'ipp/decg729.c' || echo '$(srcdir)/'`ipp/decg729.c

ipp/codec_g729nofp_la-encg729.lo: ipp/encg729.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729nofp_la-encg729.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729nofp_la-encg729.Tpo -c -o ipp/codec_g729nofp_la-encg729.lo `test -f 'ipp/encg729.c' || echo '$(srcdir)/'`ipp/encg729.c
	mv -f ipp/$(DEPDIR)/codec_g729nofp_la-encg729.Tpo ipp/$(DEPDIR)/codec_g729nofp_la-encg729.Plo
#	source='ipp/encg729.c' object='ipp/codec_g729nofp_la-encg729.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729nofp_la-encg729.lo `test -f 'ipp/encg729.c' || echo '$(srcdir)/'`ipp/encg729.c

ipp/codec_g729nofp_la-owng729.lo: ipp/owng729.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729nofp_la-owng729.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729nofp_la-owng729.Tpo -c -o ipp/codec_g729nofp_la-owng729.lo `test -f 'ipp/owng729.c' || echo '$(srcdir)/'`ipp/owng729.c
	mv -f ipp/$(DEPDIR)/codec_g729nofp_la-owng729.Tpo ipp/$(DEPDIR)/codec_g729nofp_la-owng729.Plo
#	source='ipp/owng729.c' object='ipp/codec_g729nofp_la-owng729.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729nofp_la-owng729.lo `test -f 'ipp/owng729.c' || echo '$(srcdir)/'`ipp/owng729.c

ipp/codec_g729nofp_la-vadg729.lo: ipp/vadg729.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729nofp_la-vadg729.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729nofp_la-vadg729.Tpo -c -o ipp/codec_g729nofp_la-vadg729.lo `test -f 'ipp/vadg729.c' || echo '$(srcdir)/'`ipp/vadg729.c
	mv -f ipp/$(DEPDIR)/codec_g729nofp_la-vadg729.Tpo ipp/$(DEPDIR)/codec_g729nofp_la-vadg729.Plo
#	source='ipp/vadg729.c' object='ipp/codec_g729nofp_la-vadg729.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729nofp_la-vadg729.lo `test -f 'ipp/vadg729.c' || echo '$(srcdir)/'`ipp/vadg729.c

ipp/codec_g729nofp_la-aux_tbls.lo: ipp/aux_tbls.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -MT ipp/codec_g729nofp_la-aux_tbls.lo -MD -MP -MF ipp/$(DEPDIR)/codec_g729nofp_la-aux_tbls.Tpo -c -o ipp/codec_g729nofp_la-aux_tbls.lo `test -f 'ipp/aux_tbls.c' || echo '$(srcdir)/'`ipp/aux_tbls.c
	mv -f ipp/$(DEPDIR)/codec_g729nofp_la-aux_tbls.Tpo ipp/$(DEPDIR)/codec_g729nofp_la-aux_tbls.Plo
#	source='ipp/aux_tbls.c' object='ipp/codec_g729nofp_la-aux_tbls.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(codec_g729nofp_la_CFLAGS) $(CFLAGS) -c -o ipp/codec_g729nofp_la-aux_tbls.lo `test -f 'ipp/aux_tbls.c' || echo '$(srcdir)/'`ipp/aux_tbls.c

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf ipp/.libs ipp/_libs
	-rm -rf itu/g.723.1a/.libs itu/g.723.1a/_libs
	-rm -rf itu/g.729a/.libs itu/g.729a/_libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) config.h
installdirs:
	for dir in "$(DESTDIR)$(moddir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-rm -f ipp/$(DEPDIR)/$(am__dirstamp)
	-rm -f ipp/$(am__dirstamp)
	-rm -f itu/g.723.1a/$(DEPDIR)/$(am__dirstamp)
	-rm -f itu/g.723.1a/$(am__dirstamp)
	-rm -f itu/g.729a/$(DEPDIR)/$(am__dirstamp)
	-rm -f itu/g.729a/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-modLTLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR) ipp/$(DEPDIR) itu/g.723.1a/$(DEPDIR) itu/g.729a/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-modLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-data-hook

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR) ipp/$(DEPDIR) itu/g.723.1a/$(DEPDIR) itu/g.729a/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-modLTLIBRARIES

.MAKE: install-am install-data-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-generic clean-libtool clean-modLTLIBRARIES ctags dist \
	dist-all dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-data-hook install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-modLTLIBRARIES install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-modLTLIBRARIES


install-data-hook:
	rm -f "${DESTDIR}${moddir}"/codec_g72[39]*.la;
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
